"""add_knowledge_engine

Revision ID: 23cf72707bdb
Revises: e279df183edb
Create Date: 2026-06-17 06:31:20.427818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.models


# revision identifiers, used by Alembic.
revision: str = '23cf72707bdb'
down_revision: Union[str, Sequence[str], None] = 'e279df183edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_collections_user_id'), 'knowledge_collections', ['user_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('note_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['knowledge_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_sources_collection_id'), 'knowledge_sources', ['collection_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_note_id'), 'knowledge_sources', ['note_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_user_id'), 'knowledge_sources', ['user_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_source_id'), 'knowledge_chunks', ['source_id'], unique=False)
    op.create_table('knowledge_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_source_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_relationships_source_id'), 'knowledge_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_relationships_target_source_id'), 'knowledge_relationships', ['target_source_id'], unique=False)
    op.create_table('knowledge_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_tags_source_id'), 'knowledge_tags', ['source_id'], unique=False)
    op.create_table('knowledge_embeddings',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('vector', app.models.models.SafeVector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_tags_source_id'), table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    op.drop_index(op.f('ix_knowledge_relationships_target_source_id'), table_name='knowledge_relationships')
    op.drop_index(op.f('ix_knowledge_relationships_source_id'), table_name='knowledge_relationships')
    op.drop_table('knowledge_relationships')
    op.drop_index(op.f('ix_knowledge_chunks_source_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_sources_user_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_note_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_collection_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_knowledge_collections_user_id'), table_name='knowledge_collections')
    op.drop_table('knowledge_collections')
    # ### end Alembic commands ###
