"""add meeting minutes

Revision ID: 3106bf90bbd6
Revises: b2d4e6f8a1c3
Create Date: 2026-06-17 06:06:42.219352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3106bf90bbd6'
down_revision: Union[str, Sequence[str], None] = 'b2d4e6f8a1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_minutes',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('discussion_points', sa.Text(), nullable=False),
    sa.Column('decisions', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('action_items', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_minutes')
    # ### end Alembic commands ###
