"""add note embeddings

Revision ID: 3ceeb5d03c44
Revises: 3106bf90bbd6
Create Date: 2026-06-17 06:13:38.930286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.models


# revision identifiers, used by Alembic.
revision: str = '3ceeb5d03c44'
down_revision: Union[str, Sequence[str], None] = '3106bf90bbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension if we are on PostgreSQL
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_embeddings',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('note_vector', app.models.models.SafeVector(1536), nullable=True),
    sa.Column('transcript_vector', app.models.models.SafeVector(1536), nullable=True),
    sa.Column('summary_vector', app.models.models.SafeVector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_embeddings')
    # ### end Alembic commands ###
