"""add provider to emails

Revision ID: 80c8c00a92c4
Revises: 3dbc66a7d8a2
Create Date: 2026-06-17 06:20:53.565163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c8c00a92c4'
down_revision: Union[str, Sequence[str], None] = '3dbc66a7d8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_emails', sa.Column('provider', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_emails', 'provider')
    # ### end Alembic commands ###
