"""add deleted records

Revision ID: a1cc5570f74e
Revises: c0acaee2c1b5
Create Date: 2026-06-16 22:49:02.025342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cc5570f74e'
down_revision: Union[str, Sequence[str], None] = 'c0acaee2c1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_records_id'), 'deleted_records', ['id'], unique=False)
    op.create_index(op.f('ix_deleted_records_record_id'), 'deleted_records', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_records_record_id'), table_name='deleted_records')
    op.drop_index(op.f('ix_deleted_records_id'), table_name='deleted_records')
    op.drop_table('deleted_records')
    # ### end Alembic commands ###
