"""add note enhancements

Revision ID: e279df183edb
Revises: 80c8c00a92c4
Create Date: 2026-06-17 06:24:41.660461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e279df183edb'
down_revision: Union[str, Sequence[str], None] = '80c8c00a92c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_enhancements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('enhancement_type', sa.String(), nullable=False),
    sa.Column('structured_data', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_enhancements_note_id'), 'note_enhancements', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_enhancements_note_id'), table_name='note_enhancements')
    op.drop_table('note_enhancements')
    # ### end Alembic commands ###
